//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Energy_printer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONFIG_DATA_LABEL
    {
        public int ID_LABEL { get; set; }
        public string LABEL_TYPE { get; set; }
        public decimal MARG_LEFT_1 { get; set; }
        public decimal MARG_RIGHT_1 { get; set; }
        public decimal MARG_TOP_1 { get; set; }
        public decimal MARG_BOTTOM_1 { get; set; }
        public decimal MARG_LEFT_2 { get; set; }
        public decimal MARG_RIGHT_2 { get; set; }
        public decimal MARG_TOP_2 { get; set; }
        public decimal MARG_BOTTOM_2 { get; set; }
        public string UNIT { get; set; }
    }
}
