//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Energy_printer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_LABEL
    {
        public int ID_LABEL { get; set; }
        public string LABEL_NAME { get; set; }
        public string REF_TYPE { get; set; }
        public string DEFROST_SYSTEM { get; set; }
        public string DOORTYPE { get; set; }
        public string ICE_SERVICE { get; set; }
        public string CUST_NAME { get; set; }
        public string MODEL { get; set; }
        public string CAB_SIZE { get; set; }
        public int ENERGY_COST { get; set; }
        public int LOW_SIMILAR_MODEL { get; set; }
        public int HIGH_SIMILAR_MODEL { get; set; }
        public int LOW_AMOUNT { get; set; }
        public int HIGH_AMOUNT { get; set; }
        public string ENERGY_LOGO { get; set; }
        public string PART_NUMBER { get; set; }
        public int MODEL_KW { get; set; }
        public int LOW_KW { get; set; }
        public int HIGH_KW { get; set; }
        public string TYPE { get; set; }
        public string RANGE { get; set; }
    }
}
