//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Energy_printer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JZAPPROVALEntities : DbContext
    {
        public JZAPPROVALEntities()
            : base("name=JZAPPROVALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DATA_LABEL> DATA_LABEL { get; set; }
        public virtual DbSet<CONFIG_DATA_LABEL> CONFIG_DATA_LABEL { get; set; }
    }
}
